### ISSUE TITLE
invalid api key ?

### ISSUE THREAD

**Issue by FengXMGeek** [JamitLabs/BestPracticeForAVS#1]
I run this app,but it show invalid api key . I used api key in Security Profile. why ?and the api key will change in th  Security Profile everyTime! pelase help me.

**Comment by jackdaniels92** [comment]
I have the same problem. The app crashes if the application launcher startet with a java lang error: Invalid API key. I did exactly the same as you described in your readme file. Checked via the gradle build signing options, if my keystore is found and accessed correctly. But I still receive the message: "java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jamitlabs.bespracticeavs/com.jamitlabs.bestpracticeavs.AlexaVoiceServiceActivity}: java.lang.IllegalArgumentException: Invalid API Key"
Thanks for your help and best regards, Daniel

**Comment by FengXMGeek** [comment]
@jackdaniels92  the project`s word of BestPractice is spelled worng !

**Comment by DariuschDideban** [comment]
Hey @FengXMGeek 
Where exactly is the word of BestPractice spelled wrong? Somewhere in my Readme or in the project? 

And @jackdaniels92 did this already solved your problem?
Sorry for the late answer!

**Comment by jackdaniels92** [comment]
Hey @DariuschDideban
Thanks for your reply. Unfortunately, I still have the same problem and I'm not able to test your app. Same fatal exception from main.

**Comment by DariuschDideban** [comment]
Hey @jackdaniels92 and @FengXMGeek 
I think i found the mistake. So i went through all the steps and could reproduce the mistake.
Can you give this a try? Go to the build.gradle of the app module and in the following part change this specific part of the application id: bespracticeavs to bestpracticeavs! The t is actually missing..

That is how the default config should look and which worked for me.

defaultConfig {
        applicationId "com.jamitlabs.bestpracticeavs"
        minSdkVersion 22
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.releaseConfig
    }

**Comment by jackdaniels92** [comment]
Thank you @DariuschDideban 
This little spelling mistake solved the problem: Everything works pretty well!
