### ISSUE TITLE
Not able to connect my custom skills using this project.

### ISSUE THREAD

**Issue by ankiitmaisuria** [JamitLabs/BestPracticeForAVS#3]
Thank you for providing the sample project. I run the application its working fine. I changed the Keystore.jks and api-key.txt according to my configuration. I have added the Product_Id too.
If I will ask "What's weather today?" its working fine. But my problem is to connect my custom alexa skills..Please help me out.  I want to connect with my own custom skills. Please tell me what I have to do next.

Thanks.

**Comment by ankiitmaisuria** [comment]
Its working now...Thanks for no help from anyone...

**Comment by Birdr518** [comment]
Hi @ankitmaisuriya What did you do to make your custom skill work? I habe exactly the same issue...
